# Starship Config File
## This is a modified version of the "Tokyo Night" Starship preset | https://starship.rs/presets/tokyo-night

# Color scheme taken from https://www.colourlovers.com/palette/580974/Adrift_in_Dreams
## Color Palette
### Sunlit Sea = #cff09e
### Sea Foaming = #a8dba8
### Sea Showing Green = #79bd9a
### There We Could Sail = #3b8686
### Adrift in Dreams = #0b486b
## Other Misc Colors
### Bright green = #a8f972
### Dark Blue = #1d2230

# Requirements
## Nerd Font needs to be installed - using "JetBrainsMono Nerd Font" | https://www.nerdfonts.com/font-downloads
### Install with brew: "brew install --cask font-jetbrains-mono-nerd-font"

# Prompt Formatting
format = """
[ $os $username](bg:#79bd9a fg:#000000)\
[](bg:#3b8686 fg:#79bd9a)\
$directory\
[](fg:#3b8686 bg:#0b486b)\
$git_branch\
$git_status\
[ ](fg:#0b486b)\
$aws\
$docker_context\
$nodejs\
$python\
$terraform\
$time (bg:#79bd9a fg:#79bd9a)\
\n$shell$character"""

# Custom Settings
[directory]
style = "fg:#e3e5e5 bg:#3b8686"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
always_show_remote = true
style = "bg:#0b486b"
format = "[[ $symbol $branch ](fg:#769ff0 bg:#0b486b)]($style)"

[git_status]
style = "bg:#0b486b"
format = "[[($all_status$ahead_behind )](fg:#769ff0 bg:#0b486b)]($style)"

[os]
format = "$symbol"
disabled = false

[shell]
style = "fg:#a8f972"
powershell_indicator = 'pwsh >_'
unknown_indicator = 'mystery shell >'
disabled = false

[time]
disabled = false
time_format = "%T" # Hour:Minute:Second Format # https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html
style = "fg:#a8f972"
format = "[  $time ]($style)"

[username]
style_user = "bg:#79bd9a fg:000000"
format = "[$user]($style) "
disabled = false
show_always = true


# Edited version of the Nerd Font symbols loaded from the Starship preset (i.e. 'starship preset nerd-font-symbols -o ~/.config/starship.toml')
[aws]
symbol = "  "

[docker_context]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpine = " "
AlmaLinux = " "
Amazon = " "
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
HardenedBSD = "󰞌 "
Kali = " "
Linux = " "
Macos = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[terraform]
symbol = "󱁢 "
